Conflux-Chain/sirius-next

packages/common/components/ActionButton/index.tsx
packages/common/dist/components/ActionButton/index.d.ts
packages/common/dist/components/ActionButton/index.d.ts.map
packages/common/dist/components/ActionButton/index.js
packages/common/dist/uno.css
packages/common/package.json
packages/common/tsconfig.json
packages/common/uno.config.ts
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/1)

feat: init unocss & add ActionButton

---

packages/common/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/20)

fix: build

---

packages/i18n/cspace/en/translation.json
packages/i18n/cspace/zh_cn/translation.json
packages/i18n/cspace/zh_cn/translationForDotNet.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/21)

fix: Validators i18n

---

.eslintrc.js
package.json
packages/common/package.json
packages/common/src/store/index.ts
packages/common/src/store/types.ts
packages/common/tsconfig.json
packages/common/tsconfig.lint.json
packages/eslint-config/package.json
packages/i18n/package.json
packages/i18n/tsconfig.json
packages/typescript-config/package.json
pnpm-lock.yaml
tsconfig.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/24)

fix: npm package

---

README.md
packages/common/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/25)

fix: readme

---

package.json
packages/common/package.json
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/27)

fix: tsup build

---

packages/common/src/utils/media.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/28)

fix: init once

---

packages/common/package.json
packages/common/src/components/AddressContainer/addressView.tsx
packages/common/src/components/AddressContainer/index.tsx
packages/common/src/components/Select/index.tsx
packages/common/src/components/Select/select.tsx
packages/common/src/utils/address.ts
packages/common/src/utils/hooks/useGetTxnStatus.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/29)

Micro refactoring shine

---

packages/common/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/30)

feat: update version of common

---

packages/common/package.json
packages/common/src/components/CopyButton/index.tsx
packages/common/src/components/DownloadCSV/index.tsx
packages/common/src/components/Tooltip/index.tsx
packages/common/src/utils/media.ts
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/32)

fix: mobile

---

packages/common/src/utils/address.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/34)

fix: startsWith

---

packages/common/src/utils/address.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/36)

fix: return

---

packages/common/src/utils/address.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/37)

feat: skip base32 check

---

package.json
packages/common/package.json
packages/common/src/components/AddressContainer/CoreAddressContainer.tsx
packages/common/src/components/AddressContainer/EVMAddressContainer.tsx
packages/common/src/components/AddressContainer/addressSwitcher.tsx
packages/common/src/components/AddressContainer/addressView.tsx
packages/common/src/components/AddressContainer/types.ts
packages/common/src/utils/address.test.ts
packages/common/src/utils/address.ts
packages/common/src/utils/index.test.ts
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/38)

feat: address optimize

---

.husky/pre-commit
package.json
packages/common/src/components/AddressContainer/CoreAddressContainer.tsx
packages/common/src/components/AddressContainer/EVMAddressContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/41)

fix: evm & core

---

packages/common/package.json
packages/common/src/utils/address.ts
packages/common/src/utils/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/46)

fix: address type

---

packages/i18n/cspace/zh_cn/translation.json
packages/i18n/evm/base/zh_cn/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/51)

fix: learnMore

---

packages/i18n/cspace/en/translation.json
packages/i18n/evm/base/en/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/52)

fix: 1559 i18n

---

packages/common/package.json
packages/common/src/components/Charts/config.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/55)

fix: data formatter

---

packages/common/package.json
packages/i18n/cspace/en/translation.json
packages/i18n/cspace/zh_cn/translation.json
packages/i18n/evm/base/en/translation.json
packages/i18n/evm/base/zh_cn/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/56)

feat: update i18n

---

packages/common/package.json
packages/common/src/components/Text/index.tsx
packages/common/src/components/Tooltip/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/58)

fix: support hide tooltip

---

packages/common/src/utils/cache.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/63)

feat: add fetchWithCache util

---

packages/common/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/64)

feat: update version

---

packages/common/package.json
packages/common/src/components/AddressContainer/addressSwitcher.tsx
packages/common/src/components/Text/index.tsx
packages/common/src/components/Tooltip/index.tsx
packages/common/src/components/TransactionAction/coreTransactionAction.tsx
packages/common/src/components/TransactionAction/evmTransactionAction.tsx
packages/common/src/utils/address.ts
packages/common/src/utils/cache.ts
packages/common/src/utils/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/66)

Zg scan sync

---

packages/common/package.json
packages/common/src/utils/index.ts
packages/common/src/utils/request.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/71)

fix: fetch response handle

---

packages/common/package.json
packages/common/src/utils/hooks/useAge.ts
packages/i18n/cspace/en/translation.json
packages/i18n/cspace/zh_cn/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/73)

feat: validator detail

---

packages/common/package.json
packages/common/src/utils/address.ts
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/74)

feat: add isAddressEqual

---

packages/i18n/cspace/en/translation.json
packages/i18n/cspace/zh_cn/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/76)

fix: unlock time i18n

---

packages/i18n/cspace/en/translation.json
packages/i18n/cspace/zh_cn/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/77)

feat: add validator total income

---

packages/common/package.json
packages/common/src/components/Charts/StockChartTemplate.tsx
packages/common/src/components/Charts/config.ts
packages/common/src/components/Charts/constants.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/80)

fix: remove useHighcharts

---

packages/common/package.json
packages/common/src/components/Text/index.tsx
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/82)

feat: optimize Text component

---

packages/common/src/utils/ga.ts
packages/i18n/cspace/en/translation.json
packages/i18n/cspace/zh_cn/translation.json
packages/i18n/evm/base/en/translation.json
packages/i18n/evm/base/zh_cn/translation.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/89)

fix: change scan url to .org

---

package.json
packages/common/package.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/90)

feat: version

---

packages/common/package.json
packages/common/src/components/DownloadCSV/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/91)

feat: fix google recaptcha

---

packages/common/src/components/DownloadCSV/index.tsx
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/92)

fix: token

---

packages/common/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/93)

feat: common version

---

packages/i18n/cspace/en/translation.json
packages/i18n/evm/base/en/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/96)

fix: i18n typo

---

packages/common/package.json
packages/common/src/components/Highlight/index.tsx
packages/common/src/store/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/99)

feat: highlight

---

packages/common/package.json
packages/common/src/components/DownloadCSV/index.tsx
packages/common/src/components/Dropdown/index.tsx
packages/common/src/utils/request.ts
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/105)

fix: qs to query-string

---

packages/common/package.json
packages/common/src/components/AddressContainer/addressView.tsx
packages/common/src/components/SkeletonContainer/index.tsx
packages/common/src/utils/address.ts
packages/common/src/utils/cache.ts
packages/common/src/utils/request.ts
packages/common/src/utils/request.types.ts
packages/i18n/evm/base/en/translation.json
packages/i18n/evm/base/zh_cn/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/112)

feat: 7702

---

packages/i18n/cspace/en/translation.json
packages/i18n/cspace/zh_cn/translation.json
packages/i18n/evm/base/en/translation.json
packages/i18n/evm/base/zh_cn/translation.json
packages/i18n/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-next/115)

feat: add vyper i18n
